# Generated by Django 4.2.17 on 2025-03-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('gender', models.IntegerField(choices=[(0, 'Female'), (1, 'Male')])),
                ('blood_type', models.CharField(max_length=3)),
                ('rh_factor', models.IntegerField(choices=[(0, 'Negative'), (1, 'Positive')])),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('bmi', models.FloatField()),
                ('wait_list_days', models.IntegerField()),
                ('medical_urgency_score', models.FloatField()),
                ('hemoglobin', models.FloatField()),
                ('wbc_count', models.FloatField()),
                ('platelet_count', models.FloatField()),
                ('creatinine', models.FloatField()),
                ('alt', models.FloatField()),
                ('ast', models.FloatField()),
                ('diabetes', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('hypertension', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('previous_transplant', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('dialysis_status', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('required_organ', models.CharField(max_length=50)),
                ('antibody_screen', models.FloatField()),
                ('pra_score', models.FloatField()),
                ('donation_status', models.IntegerField(default=0)),
                ('prediction_result', models.CharField(default='not eligible', max_length=50)),
            ],
        ),
    ]
