# Generated by Django 4.2.17 on 2025-07-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocateddonortorecipient',
            name='token',
            field=models.CharField(default=0, max_length=66, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allocateddonortorecipient',
            name='transaction_hash',
            field=models.CharField(default='0x0000000000000000000000000000000000000000000000000000000000000000', max_length=66),
            preserve_default=False,
        ),
    ]
