# Generated by Django 4.2.17 on 2025-08-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0005_recipient_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocateddonortorecipient',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
