# Generated by Django 4.2.17 on 2025-08-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0006_alter_allocateddonortorecipient_transaction_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-16 13:05:00'),
            preserve_default=False,
        ),
    ]
