# Generated by Django 4.2.17 on 2025-07-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donor_Registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.FloatField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
                ('rh_factor', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1)),
                ('organ_type', models.CharField(choices=[('Kidney', 'Kidney'), ('Liver', 'Liver'), ('Heart', 'Heart'), ('Lungs', 'Lungs'), ('Pancreas', 'Pancreas')], max_length=50)),
                ('address', models.TextField()),
                ('eligibility', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('gender', models.IntegerField()),
                ('blood_type', models.CharField(max_length=2)),
                ('rh_factor', models.IntegerField()),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('bmi', models.FloatField()),
                ('systolic_bp', models.FloatField()),
                ('diastolic_bp', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('temperature_celsius', models.FloatField()),
                ('respiratory_rate', models.FloatField()),
                ('hemoglobin', models.FloatField()),
                ('wbc_count', models.FloatField()),
                ('platelet_count', models.FloatField()),
                ('creatinine', models.FloatField()),
                ('alt', models.FloatField()),
                ('ast', models.FloatField()),
                ('total_bilirubin', models.FloatField()),
                ('albumin', models.FloatField()),
                ('hiv_status', models.IntegerField()),
                ('hbv_status', models.IntegerField()),
                ('hcv_status', models.IntegerField()),
                ('cmv_status', models.IntegerField()),
                ('ebv_status', models.IntegerField()),
                ('diabetes', models.IntegerField()),
                ('hypertension', models.IntegerField()),
                ('cardiac_disease', models.IntegerField()),
                ('cancer_history', models.IntegerField()),
                ('organ_type', models.CharField(max_length=20)),
                ('organ_condition_score', models.FloatField()),
                ('donation_status', models.IntegerField(default=0)),
                ('prediction_result', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
