# Generated by Django 4.2.17 on 2025-02-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('gender', models.CharField(max_length=1)),
                ('blood_type', models.CharField(max_length=2)),
                ('rh_factor', models.CharField(max_length=1)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('bmi', models.FloatField()),
                ('systolic_bp', models.FloatField()),
                ('diastolic_bp', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('temperature_celsius', models.FloatField()),
                ('respiratory_rate', models.FloatField()),
                ('hemoglobin', models.FloatField()),
                ('wbc_count', models.FloatField()),
                ('platelet_count', models.FloatField()),
                ('creatinine', models.FloatField()),
                ('alt', models.FloatField()),
                ('ast', models.FloatField()),
                ('total_bilirubin', models.FloatField()),
                ('albumin', models.FloatField()),
                ('hiv_status', models.CharField(max_length=10)),
                ('hbv_status', models.CharField(max_length=10)),
                ('hcv_status', models.CharField(max_length=10)),
                ('cmv_status', models.CharField(max_length=10)),
                ('ebv_status', models.CharField(max_length=10)),
                ('diabetes', models.CharField(max_length=3)),
                ('hypertension', models.CharField(max_length=3)),
                ('cardiac_disease', models.CharField(max_length=3)),
                ('cancer_history', models.CharField(max_length=3)),
                ('organ_type', models.CharField(max_length=20)),
                ('organ_condition_score', models.FloatField()),
                ('donation_status', models.CharField(max_length=20)),
                ('prediction_result', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
