# Generated by Django 4.2.17 on 2025-05-03 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('gender', models.IntegerField()),
                ('blood_type', models.CharField(max_length=2)),
                ('rh_factor', models.IntegerField()),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('bmi', models.FloatField()),
                ('systolic_bp', models.FloatField()),
                ('diastolic_bp', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('temperature_celsius', models.FloatField()),
                ('respiratory_rate', models.FloatField()),
                ('hemoglobin', models.FloatField()),
                ('wbc_count', models.FloatField()),
                ('platelet_count', models.FloatField()),
                ('creatinine', models.FloatField()),
                ('alt', models.FloatField()),
                ('ast', models.FloatField()),
                ('total_bilirubin', models.FloatField()),
                ('albumin', models.FloatField()),
                ('hiv_status', models.IntegerField()),
                ('hbv_status', models.IntegerField()),
                ('hcv_status', models.IntegerField()),
                ('cmv_status', models.IntegerField()),
                ('ebv_status', models.IntegerField()),
                ('diabetes', models.IntegerField()),
                ('hypertension', models.IntegerField()),
                ('cardiac_disease', models.IntegerField()),
                ('cancer_history', models.IntegerField()),
                ('organ_type', models.CharField(max_length=20)),
                ('organ_condition_score', models.FloatField()),
                ('donation_status', models.IntegerField(default=0)),
                ('prediction_result', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='donor_Registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('gender', models.IntegerField()),
                ('age', models.IntegerField(default=30)),
                ('blood_type', models.CharField(max_length=2)),
                ('rh_factor', models.IntegerField()),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('eligibility', models.CharField(max_length=50)),
                ('organ_type', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
