# Generated by Django 4.2.17 on 2025-02-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionrecord',
            name='cancer_history',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='cardiac_disease',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='cmv_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='diabetes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='donation_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='ebv_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='gender',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='hbv_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='hcv_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='hiv_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='hypertension',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predictionrecord',
            name='rh_factor',
            field=models.IntegerField(),
        ),
    ]
