# Generated by Django 4.2.17 on 2025-05-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_registered',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2),
        ),
        migrations.AlterField(
            model_name='donor_registered',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='donor_registered',
            name='rh_factor',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1),
        ),
    ]
