# Generated by Django 4.2.17 on 2025-05-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_alter_donor_registered_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_registered',
            name='organ_type',
            field=models.CharField(choices=[('Kidney', 'Kidney'), ('Liver', 'Liver'), ('Heart', 'Heart'), ('Lungs', 'Lungs'), ('Pancreas', 'Pancreas')], max_length=50),
        ),
    ]
