# Generated by Django 4.2.17 on 2025-03-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_alter_predictionrecord_cancer_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionrecord',
            name='donation_status',
            field=models.IntegerField(default=0),
        ),
    ]
