# Generated by Django 4.2.17 on 2025-07-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor_registered',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
    ]
