# Generated by Django 4.2.17 on 2025-05-03 11:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donor', '0002_rename_donor_registered_donor_registere'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='donor_Registere',
            new_name='donor_Registered',
        ),
    ]
