# Generated by Django 4.2.17 on 2025-08-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_predictionrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor_registered',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
